/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdministrativeRole;

import Business.Business;
import Business.Customer;
import Business.Order;
import Business.OrderItem;
import Business.Product;
import Business.SalesPerson;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sheetal
 */
public class ViewReports extends javax.swing.JPanel {

        private Business business;
  
    private JPanel userProcessContainer;
   
      
    public ViewReports(JPanel userProcessContainer,Business business) {
        initComponents();
          this.userProcessContainer=userProcessContainer;
  
       this.business = business;
       
       cmbsalespersonlist.removeAllItems();
        for (SalesPerson salesPerson : business.getSalesPersonDirectory().getSalesPersonList()) {
        cmbsalespersonlist.addItem(salesPerson);
        }
    
    for(Product p : business.getProductCatalog().getProductList())
    {
        
    }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnbestproduct = new javax.swing.JButton();
        txtbestproduct = new javax.swing.JTextField();
        btnbestCustomer = new javax.swing.JButton();
        txtbestcustomer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbsalespersonlist = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        txtbelowtargetprice = new javax.swing.JTextField();
        btnproductabovetarget = new javax.swing.JButton();
        txtproductabovetargetprice = new javax.swing.JTextField();
        btnviewtopsalesperson = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSalesPerson = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnbestproduct.setText("Best Product");
        btnbestproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbestproductActionPerformed(evt);
            }
        });

        btnbestCustomer.setText("Best Customer");
        btnbestCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbestCustomerActionPerformed(evt);
            }
        });

        jLabel1.setText("SalesPerson");

        cmbsalespersonlist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Product below target price");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnproductabovetarget.setText("Product Above Target Price");
        btnproductabovetarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductabovetargetActionPerformed(evt);
            }
        });

        txtproductabovetargetprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductabovetargetpriceActionPerformed(evt);
            }
        });

        btnviewtopsalesperson.setText("View Top three SalesPersons");
        btnviewtopsalesperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewtopsalespersonActionPerformed(evt);
            }
        });

        tblSalesPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "SalesPerson Name"
            }
        ));
        jScrollPane2.setViewportView(tblSalesPerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnbestCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbestcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnbestproduct)
                        .addGap(219, 219, 219)
                        .addComponent(txtbestproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnviewtopsalesperson)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addComponent(btnproductabovetarget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbsalespersonlist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtbelowtargetprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtproductabovetargetprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbestproduct)
                    .addComponent(txtbestproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnbestCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txtbestcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbsalespersonlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtbelowtargetprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproductabovetarget)
                    .addComponent(txtproductabovetargetprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnviewtopsalesperson)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbestproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbestproductActionPerformed
        Product p = business.getProductCatalog().bestproduct();
        txtbestproduct.setText(p.getProductName());
    }//GEN-LAST:event_btnbestproductActionPerformed

    private void btnbestCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbestCustomerActionPerformed
       Customer c = business.getCustomerDirectory().bestCustomer();
        txtbestcustomer.setText(c.getFirstName());
    }//GEN-LAST:event_btnbestCustomerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int count=0;
        SalesPerson s =(SalesPerson) cmbsalespersonlist.getSelectedItem();
      for(Order order : s.getMasterOrderCatalog_SalesPerson().getOrderCatalog())
      {
          for(OrderItem oi :order.getOrderList()){
              
              if(oi.getSalesPrice()<oi.getProduct().getTargetPrice())
              {
                  count++;
              }
              
          }
      }
      txtbelowtargetprice.setText(String.valueOf(count));
      
              
    
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnproductabovetargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductabovetargetActionPerformed
        int count=0;
        SalesPerson s =(SalesPerson) cmbsalespersonlist.getSelectedItem();
      for(Order order : s.getMasterOrderCatalog_SalesPerson().getOrderCatalog())
      {
          for(OrderItem oi :order.getOrderList()){
              
              if(oi.getSalesPrice()>oi.getProduct().getTargetPrice())
              {
                  count++;
              }
              
          }
      }
      txtproductabovetargetprice.setText(String.valueOf(count));
      
       
    }//GEN-LAST:event_btnproductabovetargetActionPerformed

    private void btnviewtopsalespersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewtopsalespersonActionPerformed
        ArrayList<Integer> local= new ArrayList<>();
        
        for(SalesPerson salesPerson : business.getSalesPersonDirectory().getSalesPersonList())
        {
            local.add(salesPerson.getSalesVolume());
        }
        Collections.sort(local, Collections.reverseOrder());
        
        DefaultTableModel dtm = (DefaultTableModel) tblSalesPerson.getModel();
        dtm.setRowCount(0);
        Object row[] = new Object[1];
        
        for(int i = 0;i<2;i++)
        {
            int quan= local.get(i);
            for(SalesPerson salesPerson : business.getSalesPersonDirectory().getSalesPersonList())
            {
                if(quan== salesPerson.getSalesVolume())
                {
                    row[0] = salesPerson;
                    dtm.addRow(row);
                }
            }
        }
    }//GEN-LAST:event_btnviewtopsalespersonActionPerformed

    private void txtproductabovetargetpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductabovetargetpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductabovetargetpriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbestCustomer;
    private javax.swing.JButton btnbestproduct;
    private javax.swing.JButton btnproductabovetarget;
    private javax.swing.JButton btnviewtopsalesperson;
    private javax.swing.JComboBox cmbsalespersonlist;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblSalesPerson;
    private javax.swing.JTextField txtbelowtargetprice;
    private javax.swing.JTextField txtbestcustomer;
    private javax.swing.JTextField txtbestproduct;
    private javax.swing.JTextField txtproductabovetargetprice;
    // End of variables declaration//GEN-END:variables
}
