package UserInterface.DoctorRole;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Business.Patient.Patient;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Security.Activity;
import Business.Security.SessionLog;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WorkRequestCaretaker;
import Business.WorkQueue.WorkRequestDoctor;

//import static com.sun.xml.internal.ws.api.message.Packet.Status.Request;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prashant
 */
public class AssignPatientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchoolDoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Patient patient;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EnterpriseDirectory entDirectory;
    private SessionLog session;

    public AssignPatientsJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EnterpriseDirectory entDirectory,SessionLog session) {
        initComponents();
        this.userProcessContainer = userProcessContainer;

        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.entDirectory = entDirectory;
        patient = new Patient();
            this.session=session;
          Activity a = session.getActivityDirectory().addActivity();
        a.setActivityTime(new Date());
        a.setPanelName("AssignPatientsJPanel");
        lblenterpriseName.setText(enterprise.getName());
        populateChild();

    }

    public void populateChild() {
        DefaultTableModel model = (DefaultTableModel) showPatient.getModel();

        model.setRowCount(0);

        for (WorkRequest request : ((DoctorOrganization) organization).getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = ((WorkRequestDoctor) request).getPatient().getName();
            row[2] = request.getSender().getEmployee().getEmployeeName();
            row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getEmployeeName();
            row[4] = request.getStatusatDoctor();
            row[5] = ((WorkRequestDoctor) request).getProblem();

            model.addRow(row);
        }

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        enterpriseLabel = new javax.swing.JLabel();
        btnreqCaregiver = new javax.swing.JButton();
        lblenterpriseName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showPatient = new javax.swing.JTable();
        btnViewImage = new javax.swing.JButton();
        lblviewImage = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 255, 255));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("ENTERPRISE");

        btnreqCaregiver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreqCaregiver.setText("REQUEST CAREGIVER");
        btnreqCaregiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreqCaregiverActionPerformed(evt);
            }
        });

        lblenterpriseName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblenterpriseName.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DOCTOR WORK AREA");

        showPatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PATIENT NAME", "REQUEST", "SENDER", "RECEIVER", "STATUS", "BEHAVIOURAL PROBLEM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(showPatient);
        if (showPatient.getColumnModel().getColumnCount() > 0) {
            showPatient.getColumnModel().getColumn(0).setResizable(false);
            showPatient.getColumnModel().getColumn(1).setResizable(false);
            showPatient.getColumnModel().getColumn(2).setResizable(false);
            showPatient.getColumnModel().getColumn(3).setResizable(false);
            showPatient.getColumnModel().getColumn(4).setResizable(false);
            showPatient.getColumnModel().getColumn(5).setResizable(false);
        }

        btnViewImage.setBackground(new java.awt.Color(0, 0, 0));
        btnViewImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewImage.setForeground(new java.awt.Color(255, 255, 255));
        btnViewImage.setText("View Image");
        btnViewImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewImageActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<< BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(665, 665, 665)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblenterpriseName))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(btnreqCaregiver, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewImage)
                                .addGap(72, 72, 72)
                                .addComponent(lblviewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblenterpriseName)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblviewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnViewImage)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreqCaregiver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnreqCaregiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreqCaregiverActionPerformed

        int selectedRow = showPatient.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select Child to proceed");
            return;
        }
        // WorkRequestCaretaker request = new WorkRequestCaretaker();
        WorkRequestDoctor request = (WorkRequestDoctor) showPatient.getValueAt(selectedRow, 0);
        if ((request.getStatusatDoctor().equals("Pending")) || (request.getStatusatDoctor().equals("Processing"))||(request.getStatusatDoctor().equals("Sent")))
        {
            JOptionPane.showMessageDialog(this, "You have to process the request first");
            return;
        }
       // request.setStatusatCaretaker("Sent");
        //request.setSender(userAccount);

        patient = (Patient) request.getPatient();
        RequestCaregiverJPanel processWorkRequestJPanel = new RequestCaregiverJPanel(userProcessContainer, userAccount, enterprise, entDirectory, request, patient,session);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreqCaregiverActionPerformed

    private void btnViewImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewImageActionPerformed
      
        
        int row = showPatient.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            WorkRequestDoctor wr = (WorkRequestDoctor) showPatient.getValueAt(row, 0);
            if((wr.getPatient().getImage()).length()==0)
            {
             JOptionPane.showMessageDialog(this, "Image not uploaded", "Warning", JOptionPane.WARNING_MESSAGE);
             return;
            }
            else
            lblviewImage.setIcon(new ImageIcon(wr.getPatient().getImage()));

        }
    }//GEN-LAST:event_btnViewImageActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewImage;
    private javax.swing.JButton btnreqCaregiver;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblenterpriseName;
    private javax.swing.JLabel lblviewImage;
    private javax.swing.JTable showPatient;
    // End of variables declaration//GEN-END:variables
}
