/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Patient.Patient;
import Business.Security.Activity;
import Business.Security.SessionLog;
import Business.WorkQueue.WorkRequestDoctor;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Prashant
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
     JPanel userProcessContainer;
     private WorkRequestDoctor request;
     Patient p;
     int age;
      String address;
     String behaviouralProblem;
     Date admissionDate;
     DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
     SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
     private SessionLog session;
     
    public ProcessWorkRequestJPanel(JPanel upc,WorkRequestDoctor request,Patient p,SessionLog session) {
        initComponents();
        userProcessContainer=upc;
        this.request=request;
        this.p = p;
        this.session=session;
        address = null;
        admissionDate = null;
        behaviouralProblem=null;
        this.session=session;
          Activity a = session.getActivityDirectory().addActivity();
        a.setActivityTime(new Date());
        a.setPanelName("ProcessWorkRequestJPanel");
    }
    
//     public void populateDetails(){
//        if(p.!=null){
//            for( p :p.){
//                address = ds.getAddress();
//                disability = ds.getDisability();
//                admissionDate = ds.getDate();
//            }
//            disabilityjTextField3.setText(disability);
//            String str = String.valueOf(address);
//            
//            datejTextField.setText(String.valueOf(admissionDate));
//         
//            disabilityjTextField3.setEditable(false);
//            datejTextField.setEditable(false);
//            enablejButton.setEnabled(true);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbResult = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtprescription = new javax.swing.JTextArea();
        cmbbehaviouralProblem = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(204, 255, 255));

        submitJButton.setBackground(new java.awt.Color(0, 0, 0));
        submitJButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("SUBMIT RESULT");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("RESULT");

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PATIENT'S BEHAVIOURAL PROBLEM");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CHECKUP DATE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("DOCTOR'S CONSULTANCY");

        cmbResult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbResult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Positive", "Negative" }));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("PRESCRIPTION");

        txtprescription.setColumns(20);
        txtprescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprescription.setRows(5);
        jScrollPane2.setViewportView(txtprescription);

        cmbbehaviouralProblem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbbehaviouralProblem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please specify Patient's problem", "Angry Outbursts and Physical Aggression", "Hand-wringing, Pacing and Rocking", "Accusing Loved Ones of Wrongdoing and Hallucinating", "Repeating Stories and Leaving the House Unassisted", "Sleep Problems and Sundowning" }));
        cmbbehaviouralProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbehaviouralProblemActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/article-2258782-1684F84D000005DC-999_634x423.jpg"))); // NOI18N

        jDateChooser2.setName("JDateChooser1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(601, 601, 601)
                .addComponent(jLabel6)
                .addGap(777, 946, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbResult, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbbehaviouralProblem, javax.swing.GroupLayout.Alignment.LEADING, 0, 391, Short.MAX_VALUE))
                                .addGap(204, 204, 204))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(88, 88, 88)
                        .addComponent(submitJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbbehaviouralProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        String BehaviouralProblem = cmbbehaviouralProblem.getSelectedItem().toString();
        String result=cmbResult.getSelectedItem().toString();
        String prescription = txtprescription.getText();
        jDateChooser2.getJCalendar().setMinSelectableDate(new Date()); 
       
       // Patient pt = (Patient)request.getPatient();
       // PatientDirectory patientDetails = pt.addpatientDetails();
       
      
          //try {
            // patientDetails.setChkupdate(df.parse(datejTextField.getText()));
        // } catch (ParseException ex) {
           //  Logger.getLogger(ProcessWorkRequestJPanel.class.getName()).log(Level.SEVERE, null, ex);
           //  JOptionPane.showMessageDialog(this, "Enter correct date format");
           //  return;
         //}
         
        
//        try{ childDir.setDisability(disabilityjTextField3.getText());}
//       catch(NumberFormatException ad)
//       { JOptionPane.showMessageDialog(this, " Please Enter Disability of the Child ");
//       return;
//       }
        
         if(BehaviouralProblem.equals("Please specify Patient's problem"))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Behavioural Problem of the Patient");
            return;
        }
         
         
         
         else if(jDateChooser2.getJCalendar()==null)
         {
             JOptionPane.showMessageDialog(this,"Please Enter Date of Submission");
            return; 
         }
         
         else if(prescription.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please enter prescription for the patient");
            return;
        }
         
        else if(result.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Result of the patient");
            return;
        }
        
        else 
        {
            request.setAssignment(result);
            request.setProblem(BehaviouralProblem);
            request.setPrescription(prescription);
             request.setStatusatDoctor("Completed");
             request.setCheckupDate(jDateChooser2.getDate());
             JOptionPane.showMessageDialog(this,"Health information of the patient Submitted","Information",JOptionPane.INFORMATION_MESSAGE);
             txtprescription.setText("");
             cmbbehaviouralProblem.setSelectedItem("Please specify Patient's Problem");
            
            
        }
       

//        
       
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AssignPatienttoDoctorJPanel dwjp = (AssignPatienttoDoctorJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cmbbehaviouralProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbehaviouralProblemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbehaviouralProblemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox cmbResult;
    private javax.swing.JComboBox cmbbehaviouralProblem;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextArea txtprescription;
    // End of variables declaration//GEN-END:variables
}
