/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Patient;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheetal
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientJPanel
     */
    private Patient patientDetails;
    
    public CreatePatientJPanel( Patient pd) {
        initComponents();
        this.patientDetails=pd;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtpharmacy = new javax.swing.JTextField();
        txtpatientID = new javax.swing.JTextField();
        txtpatientName = new javax.swing.JTextField();
        txtdoctorName = new javax.swing.JTextField();
        btncreatePatient = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Patient Details");

        jLabel2.setText("Patient ID");

        jLabel3.setText("Patient Name");

        jLabel4.setText("Patient Age");

        jLabel5.setText("Primary Doctor Name");

        jLabel6.setText("Preferred Pharmacy");

        txtpatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientIDActionPerformed(evt);
            }
        });

        txtpatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientNameActionPerformed(evt);
            }
        });

        btncreatePatient.setText("Create Patient");
        btncreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatePatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(156, 156, 156)
                                .addComponent(txtpatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(124, 124, 124))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(87, 87, 87)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpatientID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btncreatePatient)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(txtpharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(btncreatePatient)
                .addGap(227, 227, 227))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatePatientActionPerformed
       try
       {
           boolean flag =false;
           flag =validator();
           if(flag)
        {
        patientDetails.setPatientID(txtpatientID.getText().trim());
            
        patientDetails.setPatientName(txtpatientName.getText().trim());
           
        patientDetails.setAge(Integer.parseInt(txtage.getText().trim()));
                
        patientDetails.setDoctorName(txtdoctorName.getText().trim());
       
        patientDetails.setPharmacyName(txtpharmacy.getText().trim());
             
         
         JOptionPane.showMessageDialog(null,"Patient Details saved sucessfully");
         
         txtpatientID.setText("");
         txtpatientName.setText("");
         txtage.setText("");
         txtdoctorName.setText("");
         txtpharmacy.setText("");
        
       }
       }
       catch(NumberFormatException e)
       {
           JOptionPane.showMessageDialog(this, "Please enter Age in numbers", "", JOptionPane.PLAIN_MESSAGE);
           
       }
    }
       public boolean validator()
       {
            if((txtpatientID.getText().trim().length()) == 0)
            { JOptionPane.showMessageDialog(this,"Please enter Patient ID");
                   return false;}
            
              else  if((txtpatientName.getText().trim().length()) == 0)
              {JOptionPane.showMessageDialog(this,"Please enter Patient Name");
                   return false;}
              
              else if(!txtpatientName.getText().matches("^[a-zA-Z]*$"))
             {JOptionPane.showMessageDialog(this,"Please enter Patient Name in proper format");
                   return false;}
                  
            else if((txtage.getText().trim().length()) == 0)
            {JOptionPane.showMessageDialog(this,"Please enter Patient Age");
                   return false;}
                     
                 
            else if((txtdoctorName.getText().trim().length()) == 0)
            {   JOptionPane.showMessageDialog(this,"Please enter Doctor Name");
                   return false;}
            
             else if(!txtdoctorName.getText().matches("^[a-zA-Z]+$"))
             {JOptionPane.showMessageDialog(this,"Please enter Doctor Name in proper format");
                   return false;}
                  
            else if((txtpharmacy.getText().trim().length()) == 0 && (!txtpharmacy.getText().matches("\\d+\\s+([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+)" )))
            {  JOptionPane.showMessageDialog(this,"Please enter Pharmacy Name");
            return false;}
            
           
           else 
               return true;
  
    }//GEN-LAST:event_btncreatePatientActionPerformed

    private void txtpatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientNameActionPerformed

    private void txtpatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreatePatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdoctorName;
    private javax.swing.JTextField txtpatientID;
    private javax.swing.JTextField txtpatientName;
    private javax.swing.JTextField txtpharmacy;
    // End of variables declaration//GEN-END:variables
}
