/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesPerson;

import Business.Business;
import Business.Customer;
import Business.Order;
import Business.OrderItem;
import Business.SalesPerson;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sheetal
 */
public class SalesPersonOrderJPanel extends javax.swing.JPanel {

    
      private Business business;
    private JPanel userProcessContainer;
    SalesPerson s;
//    MasterOrderCatalog_SalesPerson sp;
     
  
    public SalesPersonOrderJPanel(JPanel userProcessContainer,Business business,SalesPerson s) {
        initComponents();
          this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.s=s;
       
        cmbcustomerdetails.removeAllItems();;
        for (Customer customer : business.getCustomerDirectory().getCustomerList()) {
            cmbcustomerdetails.addItem(customer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbcustomerdetails = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmborder = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        btnapprove = new javax.swing.JButton();
        btndecline = new javax.swing.JButton();

        jLabel1.setText("Customer");

        cmbcustomerdetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbcustomerdetails.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbcustomerdetailsPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbcustomerdetailsPopupMenuWillBecomeVisible(evt);
            }
        });
        cmbcustomerdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcustomerdetailsActionPerformed(evt);
            }
        });

        jLabel2.setText("Order");

        cmborder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmborderActionPerformed(evt);
            }
        });

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price", "Target Price", "Floor Price", "Ceiling Price", "Quantity", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderTable);

        btnapprove.setText("Approve");
        btnapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapproveActionPerformed(evt);
            }
        });

        btndecline.setText("Decline");
        btndecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeclineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnapprove)
                        .addGap(92, 92, 92)
                        .addComponent(btndecline))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbcustomerdetails, 0, 143, Short.MAX_VALUE)
                            .addComponent(cmborder, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbcustomerdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmborder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnapprove)
                    .addComponent(btndecline))
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapproveActionPerformed
       try{

        Order o = (Order)cmborder.getSelectedItem();
       
         
         if((business.getMainMasterOrder().findByID(o.getOrderID()))!= null)
         
         {
   
             JOptionPane.showMessageDialog(null, "Order is already approved ");  
             return;
            } 
             s.getMasterOrderCatalog_SalesPerson().addOrder(o);
             for(OrderItem oi : o.getOrderList())
             {
                 int q = oi.getQuantity();
                 s.setSalesVolume(s.getSalesVolume() + q);
                 
             }
            business.getMainMasterOrder().addOrder(o);
         JOptionPane.showMessageDialog(null, "Order approved ");
         cmborder.removeItem(o);
        
       
       }
       catch(NullPointerException e)
       {
          JOptionPane.showMessageDialog(null, "No order to approve");  
       }
    }//GEN-LAST:event_btnapproveActionPerformed

    private void btndeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeclineActionPerformed
          Customer c = (Customer)cmbcustomerdetails.getSelectedItem();
       
    //   for(Order order : c.getMasterOrderCatalog_Customer().getOrderCatalog())
         Order order =(Order)cmborder.getSelectedItem();
       { 
        c.getMasterOrderCatalog_Customer().deleteOrder(order); 
        cmborder.removeItem(order);
         //orderTable.remove();
          JOptionPane.showMessageDialog(null, "Order removed successfully ");
       
        
       }
         //  }// TODO add your handling code here:
    }//GEN-LAST:event_btndeclineActionPerformed

    private void cmbcustomerdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcustomerdetailsActionPerformed
       if (cmbcustomerdetails.getSelectedItem() != null)
        {
            Customer c = (Customer)cmbcustomerdetails.getSelectedItem();
        
                   
                    cmborder.removeAllItems();
                    for (Order order : c.getMasterOrderCatalog_Customer().getOrderCatalog()) {
                       cmborder.addItem(order);
                       
                   }
        }
    }//GEN-LAST:event_cmbcustomerdetailsActionPerformed

    private void cmbcustomerdetailsPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbcustomerdetailsPopupMenuWillBecomeInvisible
       
            
        
    }//GEN-LAST:event_cmbcustomerdetailsPopupMenuWillBecomeInvisible

    private void cmbcustomerdetailsPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbcustomerdetailsPopupMenuWillBecomeVisible

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcustomerdetailsPopupMenuWillBecomeVisible

    private void cmborderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmborderActionPerformed
      
         if (cmborder.getSelectedItem() != null)
         {
        DefaultTableModel dtm = (DefaultTableModel) orderTable.getModel();
      // Customer c = (Customer)cmbcustomerdetails.getSelectedItem();
       Order order = (Order)cmborder.getSelectedItem();
        dtm.setRowCount(0);
        //for (Order order : c.getMasterOrderCatalog_Customer().getOrderCatalog()){
            for (OrderItem orderItem : order.getOrderList()) {
              
               Object row[] = new Object[8];
            row[0] = orderItem;
            row[1] = orderItem.getProduct().getProductName();
            row[2] = orderItem.getSalesPrice();
            row[3] = orderItem.getProduct().getTargetPrice();
            row[4] = orderItem.getProduct().getFloorPrice();
            row[5] = orderItem.getProduct().getCeilingPrice();
            row[6] = orderItem.getQuantity();
            row[7] = orderItem.getSalesPrice() * orderItem.getQuantity();
            
                dtm.addRow(row);
            }
         }
    }//GEN-LAST:event_cmborderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapprove;
    private javax.swing.JButton btndecline;
    private javax.swing.JComboBox cmbcustomerdetails;
    private javax.swing.JComboBox cmborder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    // End of variables declaration//GEN-END:variables
}
