/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InitializationFile;


import Business.ProductCatalog;
import Business.Store;
import Business.StoreDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheetal
 */
public class AddInventoryJPanel extends javax.swing.JPanel {

    
    private JPanel upc;
    private StoreDirectory storeDirectory;
   
 
    public AddInventoryJPanel(JPanel upc,StoreDirectory storeDirectory) {
        initComponents();
           this.upc=upc;
        this.storeDirectory=storeDirectory;
        
        cmbstoreNames.removeAllItems();
        for (Store s : storeDirectory.getStoreList()) {
            cmbstoreNames.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbstoreNames = new javax.swing.JComboBox();
        btncreateInventory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmanufacturingDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmanufacturingPlace = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbproductCategory = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbdiscountAvailability = new javax.swing.JComboBox<>();
        btnaddtoInventory = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtproductName = new javax.swing.JTextField();
        txtmarkedPrice = new javax.swing.JTextField();
        txtsellingPrice = new javax.swing.JTextField();
        txtmanufacturerName = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();

        cmbstoreNames.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btncreateInventory.setText("GO>>");
        btncreateInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateInventoryActionPerformed(evt);
            }
        });

        jLabel3.setText("ProductName");

        jLabel4.setText("Availability");

        jLabel5.setText("MarkedPrice");

        jLabel6.setText("Selling Price");

        jLabel7.setText("Manufacturer Name");

        txtmanufacturingPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanufacturingPlaceActionPerformed(evt);
            }
        });

        jLabel9.setText("Manufaturing Date");

        jLabel10.setText("Manufacturing Place");

        cmbproductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clothing", "Electronics", "Food&Beverages", "Books&Articles" }));

        jLabel11.setText("Product Category");

        cmbdiscountAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        btnaddtoInventory.setText("Add Product");
        btnaddtoInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtoInventoryActionPerformed(evt);
            }
        });

        jLabel12.setText("Discount Availability");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtproductName)
                            .addComponent(txtmarkedPrice)
                            .addComponent(txtsellingPrice)
                            .addComponent(txtmanufacturerName)
                            .addComponent(txtmanufacturingDate)
                            .addComponent(txtmanufacturingPlace)
                            .addComponent(cmbproductCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbdiscountAvailability, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtAvailability)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnaddtoInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbstoreNames, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncreateInventory)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbstoreNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncreateInventory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtproductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmarkedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmanufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtmanufacturingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtmanufacturingPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbproductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbdiscountAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33)
                .addComponent(btnaddtoInventory)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateInventoryActionPerformed
    // Store s = (Store)cmbstoreNames.getSelectedItem();
//         NewInventoryJPanel panel = new NewInventoryJPanel(s,upc);
//        upc.add("NewInventoryJPanel", panel);
//        CardLayout layout = (CardLayout) upc.getLayout();
//        layout.next(upc);
     
    }//GEN-LAST:event_btncreateInventoryActionPerformed

    private void txtmanufacturingPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanufacturingPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanufacturingPlaceActionPerformed

    private void btnaddtoInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtoInventoryActionPerformed
    Store s = (Store)cmbstoreNames.getSelectedItem();
             try{
            Business.Product p = new Business.Product();
            p.setProductName(txtproductName.getText().trim());
            p.setManufacturer(txtmanufacturerName.getText().trim());
            p.setAvailability(Integer.parseInt(txtAvailability.getText().trim()));
            p.setManufacturingDate(txtmanufacturingDate.getText().trim());
            p.setProductCategory(cmbproductCategory.getSelectedItem().toString());
            String mp=txtmarkedPrice.getText().trim();
            p.setMarkedPrice(Double.parseDouble(mp));
            String sp= txtsellingPrice.getText().trim();
            p.setSellingPrice(Double.parseDouble(sp));
            p.setDiscountAvailability(cmbdiscountAvailability.getSelectedItem().toString());
            p.setManufacturingPlace(txtmanufacturingPlace.getText().trim());
          //  s.getInventoryDirectory().addProductinInventory(p);
            JOptionPane.showMessageDialog(null, "Product created successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        
       
        
        }

        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(null, "Wrong format", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;

        }

    }//GEN-LAST:event_btnaddtoInventoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddtoInventory;
    private javax.swing.JButton btncreateInventory;
    private javax.swing.JComboBox<String> cmbdiscountAvailability;
    private javax.swing.JComboBox<String> cmbproductCategory;
    private javax.swing.JComboBox cmbstoreNames;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtmanufacturerName;
    private javax.swing.JTextField txtmanufacturingDate;
    private javax.swing.JTextField txtmanufacturingPlace;
    private javax.swing.JTextField txtmarkedPrice;
    private javax.swing.JTextField txtproductName;
    private javax.swing.JTextField txtsellingPrice;
    // End of variables declaration//GEN-END:variables
}
