/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InitializationFile;


import Business.Product;
import Business.ProductCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheetal
 */
public class AddProductJPanel extends javax.swing.JPanel {

    private ProductCatalog productCatalog;
    private JPanel upc;
    public AddProductJPanel(ProductCatalog productCatalog,JPanel upc) {
        initComponents();
        this.productCatalog=productCatalog;
        this.upc=upc;
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnaddProduct = new javax.swing.JButton();
        txtproductName = new javax.swing.JTextField();
        txtmarkedPrice = new javax.swing.JTextField();
        txtproductdesc = new javax.swing.JTextField();
        txtmanufacturerName = new javax.swing.JTextField();
        txtmanufacturingDate = new javax.swing.JTextField();
        txtmanufacturingPlace = new javax.swing.JTextField();
        cmbproductCategory = new javax.swing.JComboBox<>();
        cmbdiscountAvailability = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product Details");

        jLabel3.setText("ProductName");

        jLabel4.setText("Availability");

        jLabel5.setText("MarkedPrice");

        jLabel6.setText("Product Desc");

        jLabel7.setText("Manufacturer Name");

        jLabel9.setText("Manufaturing Date");

        jLabel10.setText("Manufacturing Place");

        jLabel11.setText("Product Category");

        btnaddProduct.setText("Add Product");
        btnaddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddProductActionPerformed(evt);
            }
        });

        txtmanufacturingPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanufacturingPlaceActionPerformed(evt);
            }
        });

        cmbproductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clothing", "Electronics", "Food&Beverages", "Books&Articles" }));

        cmbdiscountAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        jLabel12.setText("Discount Availability");

        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtproductName)
                            .addComponent(txtmarkedPrice)
                            .addComponent(txtproductdesc)
                            .addComponent(txtmanufacturerName)
                            .addComponent(txtmanufacturingDate)
                            .addComponent(txtmanufacturingPlace)
                            .addComponent(cmbproductCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbdiscountAvailability, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtAvailability)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(btnaddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnback)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtproductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmarkedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtproductdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmanufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtmanufacturingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtmanufacturingPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbproductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbdiscountAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33)
                .addComponent(btnaddProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnback)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddProductActionPerformed

        try{
                  
       String key = txtproductName.getText();
       Product result = productCatalog.searchProductName(key);
       if(result!=null)
       {
           JOptionPane.showMessageDialog(null, "Product already exists", "Information", JOptionPane.INFORMATION_MESSAGE);
            return; 
       }
       else
       {
            Product p = new Product();
            p.setProductName(txtproductName.getText().trim());
            p.setManufacturer(txtmanufacturerName.getText().trim());
            p.setAvailability(Integer.parseInt(txtAvailability.getText().trim()));
            p.setManufacturingDate(txtmanufacturingDate.getText().trim());
            p.setProductCategory(cmbproductCategory.getSelectedItem().toString());
            String mp=txtmarkedPrice.getText().trim();
            p.setMarkedPrice(Double.parseDouble(mp));
            String sp= txtproductdesc.getText().trim();
            p.setProductdesc(sp);
            p.setDiscountAvailability(cmbdiscountAvailability.getSelectedItem().toString());
            p.setManufacturingPlace(txtmanufacturingPlace.getText().trim());
            productCatalog.addProduct(p);
            JOptionPane.showMessageDialog(null, "Product created successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
       
        }

        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(null, "Wrong format", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;

        }

    }//GEN-LAST:event_btnaddProductActionPerformed

    private void txtmanufacturingPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanufacturingPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanufacturingPlaceActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddProduct;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cmbdiscountAvailability;
    private javax.swing.JComboBox<String> cmbproductCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtmanufacturerName;
    private javax.swing.JTextField txtmanufacturingDate;
    private javax.swing.JTextField txtmanufacturingPlace;
    private javax.swing.JTextField txtmarkedPrice;
    private javax.swing.JTextField txtproductName;
    private javax.swing.JTextField txtproductdesc;
    // End of variables declaration//GEN-END:variables
}
