/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerRole;

import Business.Business;
import Business.Customer;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sheetal
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel userProcessContainer;
    public ManageCustomerJPanel( JPanel userProcessContainer,Business business) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        cmbcustomerlogin.removeAllItems();
        for (Customer customer : business.getCustomerDirectory().getCustomerList()) {
            cmbcustomerlogin.addItem(customer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbcustomerlogin = new javax.swing.JComboBox();
        btncreateOrder = new javax.swing.JButton();
        btnviewOrder = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Login >>");

        cmbcustomerlogin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbcustomerlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcustomerloginActionPerformed(evt);
            }
        });

        btncreateOrder.setText("Create Order");
        btncreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateOrderActionPerformed(evt);
            }
        });

        btnviewOrder.setText("View Order");
        btnviewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbcustomerlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btncreateOrder)
                        .addGap(56, 56, 56)
                        .addComponent(btnviewOrder)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(cmbcustomerlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncreateOrder)
                    .addComponent(btnviewOrder))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbcustomerloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcustomerloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcustomerloginActionPerformed

    private void btncreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateOrderActionPerformed
          Customer c = (Customer)cmbcustomerlogin.getSelectedItem();
          CustomerOrdersJPanel panel = new CustomerOrdersJPanel(userProcessContainer,business,c);
        userProcessContainer.add("CustomerOrdersJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btncreateOrderActionPerformed

    private void btnviewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewOrderActionPerformed
        Customer c = (Customer)cmbcustomerlogin.getSelectedItem();
          ViewOrderHistoryJPanel panel = new ViewOrderHistoryJPanel(userProcessContainer,business,c);
        userProcessContainer.add("ViewOrderHistoryJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnviewOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreateOrder;
    private javax.swing.JButton btnviewOrder;
    private javax.swing.JComboBox cmbcustomerlogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
