/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.Organization;
import Business.Patient.Image;
import Business.Patient.Patient;
import Business.Security.Activity;
import Business.Security.SessionLog;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sheetal
 */
public class ImageMemoriesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    private EnterpriseDirectory enterpriseDirectory;
    private SessionLog session;

    public ImageMemoriesJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Organization organization, EnterpriseDirectory enterpriseDirectory, SessionLog session) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.enterpriseDirectory = enterpriseDirectory;
        this.session = session;
        Activity a = session.getActivityDirectory().addActivity();
        a.setActivityTime(new Date());
        a.setPanelName("ImageMemoriesJPanel");

        cmbPatientList.removeAll();
        for (Patient p : enterprise.getPatientDirectory().getPatientlist()) {
            cmbPatientList.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnattachImage = new javax.swing.JButton();
        txtimage = new javax.swing.JTextField();
        btnattachImage1 = new javax.swing.JButton();
        txtimage1 = new javax.swing.JTextField();
        btnattachImage2 = new javax.swing.JButton();
        txtimage2 = new javax.swing.JTextField();
        cmbPatientList = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(204, 255, 255));

        btnattachImage.setBackground(new java.awt.Color(0, 0, 0));
        btnattachImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnattachImage.setForeground(new java.awt.Color(255, 255, 255));
        btnattachImage.setText("Attach Image");
        btnattachImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattachImageActionPerformed(evt);
            }
        });

        btnattachImage1.setBackground(new java.awt.Color(0, 0, 0));
        btnattachImage1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnattachImage1.setForeground(new java.awt.Color(255, 255, 255));
        btnattachImage1.setText("Attach Image");
        btnattachImage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattachImage1ActionPerformed(evt);
            }
        });

        txtimage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimage1ActionPerformed(evt);
            }
        });

        btnattachImage2.setBackground(new java.awt.Color(0, 0, 0));
        btnattachImage2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnattachImage2.setForeground(new java.awt.Color(255, 255, 255));
        btnattachImage2.setText("Attach Image");
        btnattachImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattachImage2ActionPerformed(evt);
            }
        });

        txtimage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimage2ActionPerformed(evt);
            }
        });

        cmbPatientList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbPatientList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientListActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT IMAGES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PATIENT NAME");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADD IMAGES OF GUARDIAN");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Patient-holding-hands-010.jpg"))); // NOI18N

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<< BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 435, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtimage1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtimage2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(cmbPatientList, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtimage, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnattachImage1)
                            .addComponent(btnattachImage)
                            .addComponent(btnattachImage2))))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(627, 627, 627)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(254, 254, 254))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbPatientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtimage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnattachImage1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnattachImage))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtimage2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnattachImage2))))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
JFileChooser fc = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif", "png");
    private void btnattachImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattachImageActionPerformed
        try {
            fc.setFileFilter(filter);

            int click = fc.showOpenDialog(this);
            if (click == fc.APPROVE_OPTION) {
                File f = fc.getSelectedFile();
                txtimage1.setText(f.getPath());

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please input only image files");
            return;
        }

    }//GEN-LAST:event_btnattachImageActionPerformed

    private void btnattachImage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattachImage1ActionPerformed

        try {
            fc.setFileFilter(filter);

            int click = fc.showOpenDialog(this);
            if (click == fc.APPROVE_OPTION) {
                File f = fc.getSelectedFile();
                txtimage.setText(f.getPath());

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please input only image files");
            return;
        }

    }//GEN-LAST:event_btnattachImage1ActionPerformed

    private void btnattachImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattachImage2ActionPerformed
        try {
            fc.setFileFilter(filter);
            int click = fc.showOpenDialog(this);

            if (click == fc.APPROVE_OPTION) {
                File f = fc.getSelectedFile();
                txtimage2.setText(f.getPath());

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please input only image files");
            return;
        }


    }//GEN-LAST:event_btnattachImage2ActionPerformed

    private void cmbPatientListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPatientListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Patient patient = (Patient) cmbPatientList.getSelectedItem();
        Image image = new Image();
        image.setImage1(txtimage.getText());
        image.setImage2(txtimage1.getText());
        image.setImage3(txtimage2.getText());
        patient.getImageDirectory().addImage(image);
         JOptionPane.showMessageDialog(this, "Images are uploaded");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtimage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimage1ActionPerformed

    }//GEN-LAST:event_txtimage1ActionPerformed

    private void txtimage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimage2ActionPerformed
        int click = fc.showOpenDialog(this);
        if (click == fc.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            jLabel1.setIcon(new ImageIcon(f.getPath()));
            txtimage2.setText(f.getPath());

        }
    }//GEN-LAST:event_txtimage2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnattachImage;
    private javax.swing.JButton btnattachImage1;
    private javax.swing.JButton btnattachImage2;
    private javax.swing.JComboBox cmbPatientList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtimage;
    private javax.swing.JTextField txtimage1;
    private javax.swing.JTextField txtimage2;
    // End of variables declaration//GEN-END:variables
}
