/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Patient;

import Business.Person;
import Business.PersonDirectory;
import Business.VitalSign;
import Business.VitalSignHistory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sheetal
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
   
    
    public CreatePersonJPanel(PersonDirectory personDirectory, JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.personDirectory=personDirectory;
     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtpersonName = new javax.swing.JTextField();
        btncreatePerson = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();

        jLabel1.setText("Create Person");

        jLabel2.setText("ID");

        jLabel3.setText("Person Name");

        txtpersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonNameActionPerformed(evt);
            }
        });

        btncreatePerson.setText("Create Person");
        btncreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreatePersonActionPerformed(evt);
            }
        });

        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel4.setText("Gender");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btncreatePerson))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(67, 67, 67))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(96, 96, 96)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpersonName, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(cmbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btncreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(btnback)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtpersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonNameActionPerformed

    private void btncreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreatePersonActionPerformed
        
       try{
      
        
        String ID = txtID.getText();
        
            String PersonName = txtpersonName.getText();
            
           Person result = personDirectory.searchAccount(ID,PersonName);
           
           
           if(result != null)
            {
              JOptionPane.showMessageDialog(null, "Person with same ID or name already exists", "Information", JOptionPane.INFORMATION_MESSAGE);
          
            }
            else
            {
            // if Integer.parseInt went wrong, no account will get created.
            Person persondetails = new Person();
           
            persondetails.setPersonID(ID);
            
            persondetails.setPersonName(PersonName);
            persondetails.setPersonGender(cmbGender.getSelectedItem().toString());
            
            personDirectory.createPerson(persondetails);
          
            
            JOptionPane.showMessageDialog(null, "Person created successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtID.setText("");
            txtpersonName.setText("");
            
            }
       }
       catch(NullPointerException e)
       {
            JOptionPane.showMessageDialog(null, "Please enter values", "Information", JOptionPane.ERROR_MESSAGE);
       }
       
    }

       public void populateTable() {
//   
//        DefaultTableModel dtm = (DefaultTableModel) tblpatientDetails.getModel();
//        dtm.setRowCount(0);
//        for(Patient p: person.getPatientDirectory())
//        {
//            
//            Object[] row = new Object[2];
//           
//            row[0] = p.getID();
//            row[1]=p.getName();
//            
//            dtm.addRow(row);
//        }
//         for (VitalSign vs : pt.getVitalSignHistory()) {
//
//            Object[] row =new Object[1];
//           
//            if (!vitalSignStatus(vs))
//            {
//               row[2] = "Abnormal"; 
//            }
//            else{
//                row[2] = "Normal";  
//            }
//            dtm.addRow(row);
//            
//        }  
//     
//     }
//  public boolean vitalSignStatus(VitalSign vs)
//  {
// 
//          if(pt.getAge()>=1 && pt.getAge()<=3)
//          {
//              if((vs.getRespiratoryrate()>=20 && vs.getRespiratoryrate()<=30) &&
//                (vs.getBloodpressure()>=80 && vs.getBloodpressure()<=110) &&
//                (vs.getHeartrate()>=80 && vs.getHeartrate()<=130)&&
//                (vs.getWeight()>=22 && vs.getWeight()<=31))
//              return true;
//               
//          }
//          else if(pt.getAge()==4 || pt.getAge()==5)
//          {
//              if((vs.getRespiratoryrate()>=20 && vs.getRespiratoryrate()<=30) &&
//                (vs.getBloodpressure()>=80 && vs.getBloodpressure()<=110) &&
//                (vs.getHeartrate()>=80 && vs.getHeartrate()<=120)&&
//                (vs.getWeight()>=31 && vs.getWeight()<=40))
//              return true; 
//              
//          }
//          else if(pt.getAge()>=6 && pt.getAge()<=12)
//          {
//              if((vs.getRespiratoryrate()>=20 && vs.getRespiratoryrate()<=30) &&
//                (vs.getBloodpressure()>=80 && vs.getBloodpressure()<=120) &&
//                (vs.getHeartrate()>=70 && vs.getHeartrate()<=110)&&
//                (vs.getWeight()>=41 && vs.getWeight()<=92))
//                return true;
//          }
//          else if (pt.getAge()>=13)
//          {
//              if((vs.getRespiratoryrate()>=12 && vs.getRespiratoryrate()<=20) &&
//                (vs.getBloodpressure()>=110 && vs.getBloodpressure()<=120) &&
//                (vs.getHeartrate()>=55 && vs.getHeartrate()<=105)&&
//                (vs.getWeight()>=110))
//                 return true;
//          } 
//         
//              return false;   
      
    }//GEN-LAST:event_btncreatePersonActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        PatientDetailsMgrJPanel panel = new PatientDetailsMgrJPanel(personDirectory,userProcessContainer);
        userProcessContainer.add("PatientDetailsMgrJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncreatePerson;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtpersonName;
    // End of variables declaration//GEN-END:variables
}
