/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.VitalSign;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Sheetal
 */
public class JFreeChartJPanel extends javax.swing.JPanel {

       private VitalSign vs;
    private JPanel upc;
    public JFreeChartJPanel(VitalSign vs,JPanel upc) {
        initComponents();
    
        this.vs=vs;
        this.upc=upc;
        
           int rr= (vs.getRespiratoryrate());
        int hr =vs.getHeartrate();
        int bp= vs.getBloodpressure();
        double w =vs.getWeight();
        DefaultCategoryDataset dataset =new DefaultCategoryDataset();
        dataset.setValue(rr,"", "Respiratory Rate");
        dataset.setValue(hr,"", "Heart Rate");
        dataset.setValue(bp,"", "Blood Pressure");
        dataset.setValue(w,"", "Weight");
        
//    
        org.jfree.chart.JFreeChart chart = ChartFactory.createBarChart("VitalSign", "Vital Signs","Range",dataset,PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Bar Chart for _---_",chart);
        frame.setVisible(true);
        frame.setSize(600,600); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
