/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Patient;

import Business.Person;
import Business.PersonDirectory;
import Business.VitalSign;
import Business.VitalSignHistory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sheetal
 */
public class PatientDetailsMgrJPanel extends javax.swing.JPanel {

    Person person;
    private PersonDirectory personDirectory;
    private JPanel userProcessContainer;
   
    //public PatientDetailsMgrJPanel(Person person,PersonDirectory personDirectory,PatientDirectory pd, VitalSignHistory vsh,JPanel userProcessContainer,Patient pt,VitalSign vs) {
    public PatientDetailsMgrJPanel(PersonDirectory personDirectory,JPanel userProcessContainer) {
    
        initComponents();
        this.person=person;
        this.personDirectory=personDirectory;
        this.userProcessContainer=userProcessContainer;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatePerson = new javax.swing.JButton();
        btnviewPerson = new javax.swing.JButton();

        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnviewPerson.setText("View Person");
        btnviewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnviewPerson)
                    .addComponent(btnCreatePerson))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnCreatePerson)
                .addGap(49, 49, 49)
                .addComponent(btnviewPerson)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewPersonActionPerformed
        // TODO add your handling code here:
          ViewPersonDetails panel = new ViewPersonDetails( personDirectory, userProcessContainer);
        userProcessContainer.add("ViewPersonDetails", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnviewPersonActionPerformed

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
       CreatePersonJPanel panel = new CreatePersonJPanel(  personDirectory,userProcessContainer);
        userProcessContainer.add("CreatePersonJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreatePersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnviewPerson;
    // End of variables declaration//GEN-END:variables
}
