/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Person;
import Business.VitalSign;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class UpdateJPanel extends javax.swing.JPanel {

    
VitalSign vs;
Person person;
private JPanel upc;
    public UpdateJPanel(Person person,VitalSign vs, JPanel upc) {
        initComponents();
        this.vs=vs;
        this.upc=upc;
        this.person=person;
            populateForm();
        btnsave.setEnabled(false);
    }

    private void populateForm() {
        txtrespiratoryRate.setText(String.valueOf(vs.getRespiratoryrate()));
        txtheartRate.setText(String.valueOf(vs.getHeartrate()));
        txtbloodPressure.setText(String.valueOf(vs.getBloodpressure()));
        txtweight.setText(String.valueOf(vs.getWeight()));
        
      
    }
          public boolean vitalSignStatus(VitalSign vs)
  {
 
          if(person.getPatient().getAge()>=1 && person.getPatient().getAge()<=3)
          {
              if((vs.getRespiratoryrate()>=20 && vs.getRespiratoryrate()<=30) &&
                (vs.getBloodpressure()>=80 && vs.getBloodpressure()<=110) &&
                (vs.getHeartrate()>=80 && vs.getHeartrate()<=130)&&
                (vs.getWeight()>=22 && vs.getWeight()<=31))
              return true;
               
          }
          else if(person.getPatient().getAge()==4 || person.getPatient().getAge()==5)
          {
              if((vs.getRespiratoryrate()>=20 && vs.getRespiratoryrate()<=30) &&
                (vs.getBloodpressure()>=80 && vs.getBloodpressure()<=110) &&
                (vs.getHeartrate()>=80 && vs.getHeartrate()<=120)&&
                (vs.getWeight()>=31 && vs.getWeight()<=40))
              return true; 
              
          }
          else if(person.getPatient().getAge()>=6 && person.getPatient().getAge()<=12)
          {
              if((vs.getRespiratoryrate()>=20 && vs.getRespiratoryrate()<=30) &&
                (vs.getBloodpressure()>=80 && vs.getBloodpressure()<=120) &&
                (vs.getHeartrate()>=70 && vs.getHeartrate()<=110)&&
                (vs.getWeight()>=41 && vs.getWeight()<=92))
                return true;
          }
          else if (person.getPatient().getAge()>=13)
          {
              if((vs.getRespiratoryrate()>=12 && vs.getRespiratoryrate()<=20) &&
                (vs.getBloodpressure()>=110 && vs.getBloodpressure()<=120) &&
                (vs.getHeartrate()>=55 && vs.getHeartrate()<=105)&&
                (vs.getWeight()>=110))
                 return true;
          } 
         
              return false;   
      
    }            

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbloodPressure = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtrespiratoryRate = new javax.swing.JTextField();
        txtheartRate = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel8.setText("/lb");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Vital Sign Details");

        jLabel10.setText("Respiratory Rate");

        jLabel5.setText("Heart Rate");

        jLabel6.setText(" Blood Pressure");

        jLabel7.setText("Weight");
        jLabel7.setToolTipText("");

        txtrespiratoryRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrespiratoryRateActionPerformed(evt);
            }
        });

        txtheartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtheartRateActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnsave)
                        .addGap(74, 74, 74)
                        .addComponent(btnupdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnback)))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtbloodPressure, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtweight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(82, 82, 82)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtrespiratoryRate)
                                        .addComponent(txtheartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(166, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnupdate))
                .addGap(137, 137, 137)
                .addComponent(btnback)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtrespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtheartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addContainerGap(242, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtrespiratoryRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrespiratoryRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrespiratoryRateActionPerformed

    private void txtheartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtheartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheartRateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:

        try {
            String bp = txtbloodPressure.getText();
            String hr = txtheartRate.getText();
           
            String rr =txtrespiratoryRate.getText();
            String w = txtweight.getText();

            vs.setRespiratoryrate(Integer.parseInt(rr));
            vs.setHeartrate(Integer.parseInt(hr));
            vs.setBloodpressure(Integer.parseInt(bp));
            vs.setWeight(Double.parseDouble(w));
              if(!vitalSignStatus(vs))
            {
               vs.setStatus("Abnormal"); 
            }
            else{
                 vs.setStatus("Normal");  
            }
            
       

            JOptionPane.showMessageDialog(null, "Person details successfully updated.", "Information", JOptionPane.INFORMATION_MESSAGE);
            btnsave.setEnabled(false);
            btnupdate.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Correct format required.", "Information", JOptionPane.ERROR_MESSAGE);
            btnsave.setEnabled(false);
            btnupdate.setEnabled(true);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        txtrespiratoryRate.setEnabled(true);
        txtbloodPressure.setEnabled(true);
        txtheartRate.setEnabled(true);
        txtweight.setEnabled(true);
        btnsave.setEnabled(true);
        btnupdate.setEnabled(false);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
//          upc.remove(this);
//        CardLayout layout = (CardLayout) upc.getLayout();
//        layout.previous(upc);

upc.remove(this);
        Component[] componentArray = upc.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewPersonDetails manageAccountJPanel = (ViewPersonDetails) component;
        manageAccountJPanel.populateTable();
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtbloodPressure;
    private javax.swing.JTextField txtheartRate;
    private javax.swing.JTextField txtrespiratoryRate;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
