/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Security.Activity;
import Business.Security.SessionLog;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sheetal
 */
public class AddPatientJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    private EnterpriseDirectory enterpriseDirectory;
    private SessionLog session;
     public AddPatientJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,Organization organization,EnterpriseDirectory enterpriseDirectory,SessionLog session) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.enterpriseDirectory=enterpriseDirectory;
        this.session=session;
          Activity a = session.getActivityDirectory().addActivity();
        a.setActivityTime(new Date());
        a.setPanelName("AddPatientJPanel");
    
        populatepatientDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpatient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtimage = new javax.swing.JTextField();
        txtpatientName = new javax.swing.JTextField();
        btnattachImage = new javax.swing.JButton();
        btnaddPatient = new javax.swing.JButton();
        lblpatientImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpatientAge = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtguardianName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtguardianmailID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age");

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("<< BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Address");

        tblpatient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblpatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PATIENT ID", "PATIENT NAME", "GUARDIAN NAME", "PATIENT AGE", "ADDRESS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblpatient);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient's Photo");

        txtpatientName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientNameActionPerformed(evt);
            }
        });

        btnattachImage.setBackground(new java.awt.Color(0, 0, 0));
        btnattachImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnattachImage.setForeground(new java.awt.Color(255, 255, 255));
        btnattachImage.setText("Attach Image");
        btnattachImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattachImageActionPerformed(evt);
            }
        });

        btnaddPatient.setBackground(new java.awt.Color(0, 0, 0));
        btnaddPatient.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnaddPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnaddPatient.setText("ADD PATIENT");
        btnaddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddPatientActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setText("ADD PATIENT");

        txtpatientAge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane2.setViewportView(txtaddress);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Guardian Name");

        txtguardianName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Guardian Email ID");

        txtguardianmailID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cliparti1_secretary-clip-art_05.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblpatientImage, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtimage, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnattachImage))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtpatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtguardianName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtguardianmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnback)
                        .addGap(301, 301, 301)
                        .addComponent(btnaddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtpatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35))
                                        .addComponent(txtguardianName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(13, 13, 13)
                                    .addComponent(txtpatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtguardianmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnattachImage))
                            .addGap(18, 18, 18)
                            .addComponent(btnaddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel8)
                            .addGap(51, 51, 51)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblpatientImage, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    public void populatepatientDetails()
    {
        DefaultTableModel model = (DefaultTableModel) tblpatient.getModel();
        model.setRowCount(0);
        for (Patient patient : enterprise.getPatientDirectory().getPatientlist()){
            Object[] row = new Object[5];
            row[0] = patient;
            row[1] = patient.getName();
            row[2] = patient.getGuardianName();
            row[3] = patient.getAge();
            row[4] = patient.getAddress();
            model.addRow(row);
        }
    }
    private void txtpatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientNameActionPerformed
   JFileChooser chooser = new JFileChooser();
FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");

    
    private void btnattachImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattachImageActionPerformed
        try
        {chooser.setFileFilter(filter);
        int click = chooser.showOpenDialog(this);
          
        if(click== chooser.APPROVE_OPTION)
        {
            File f = chooser.getSelectedFile();
            lblpatientImage.setIcon(new ImageIcon(f.getPath()));
            txtimage.setText(f.getPath());

        }
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, "Please input only image files");
                    return;
                }

    }//GEN-LAST:event_btnattachImageActionPerformed

    private void btnaddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddPatientActionPerformed
        // TODO add your handling code here:
        Patient patient = new Patient();

        if ((txtpatientName.getText().trim().length()==0)||(!txtpatientName.getText().matches("^[a-zA-Z]+$")))
        {
            JOptionPane.showMessageDialog(this, "Enter Alphabets in Name","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if ((txtguardianName.getText().trim().length()==0)||(!txtguardianName.getText().matches("^[a-zA-Z]+$")))
        {
            JOptionPane.showMessageDialog(this, "Enter Alphabets in Guardian Name","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if((txtpatientAge.getText().trim().length()==0)||(!(txtpatientAge.getText().matches("^[1-9]\\d*$"))))
        {
            JOptionPane.showMessageDialog(this,"Input integers for the age","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        else if ((txtaddress.getText().trim().length()==0))
        {
            JOptionPane.showMessageDialog(this, "Enter Address field","Warning",JOptionPane.WARNING_MESSAGE);
            return;
            
        }
        
        else if (txtimage.getText().trim().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Please attach image of patient","Warning",JOptionPane.WARNING_MESSAGE);
            return;
            
        }

        else{
            String name= txtpatientName.getText();
          
                Patient result = enterprise.getPatientDirectory().checkIfChiIdUserNameIsUnique(name);
           if(result != null)
            {
              JOptionPane.showMessageDialog(null, "Patient with same name already exists", "Information", JOptionPane.INFORMATION_MESSAGE);
               txtpatientName.setText("");
            txtpatientAge.setText("");
            txtaddress.setText("");
            txtimage.setText(""); 
            lblpatientImage.setIcon(null);
              return;
            }
           else
           {
                 patient.setAge(txtpatientAge.getText());
           patient.setName(txtpatientName.getText());
           patient.setGuardianName(txtguardianName.getText());
            patient.setAddress(txtaddress.getText());
            patient.setImage(txtimage.getText());
           for(Enterprise e:enterpriseDirectory.getEnterpriseList()) {
            e.getPatientDirectory().getPatientlist().add(patient);
              }
            
           JOptionPane.showMessageDialog(this,"Patient Added");
            populatepatientDetails();
            txtpatientName.setText("");
            txtguardianName.setText("");
           txtpatientAge.setText("");
            txtaddress.setText("");
            txtimage.setText("");
             lblpatientImage.setIcon(null);
            }

        }       
    }//GEN-LAST:event_btnaddPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddPatient;
    private javax.swing.JButton btnattachImage;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblpatientImage;
    private javax.swing.JTable tblpatient;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtguardianName;
    private javax.swing.JTextField txtguardianmailID;
    private javax.swing.JTextField txtimage;
    private javax.swing.JTextField txtpatientAge;
    private javax.swing.JTextField txtpatientName;
    // End of variables declaration//GEN-END:variables
}
