package UserInterface.DoctorRole;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.CaregiverOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Security.Activity;
import Business.Security.SessionLog;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WorkRequestCaretaker;
import Business.WorkQueue.WorkRequestDoctor;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Prashant
 */
public class RequestCaregiverJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestCaregiverJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private EnterpriseDirectory entdir;
    private WorkRequest req;
    private UserAccount account;
    private Patient patient;
    private SessionLog session;

    public RequestCaregiverJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EnterpriseDirectory entdir, WorkRequest req, Patient patient, SessionLog session) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.entdir = entdir;
        this.patient = patient;
        this.req = req;
        this.session = session;
        Activity a = session.getActivityDirectory().addActivity();
        a.setActivityTime(new Date());
        a.setPanelName("RequestCaregiverJPanel");
        // this.organization=organization;
        String behaviouralproblem = null;
        Date checkupdate = null;
        String prescription = null;
         valueLabel.setText(enterprise.getName());
        String name = patient.getName();
        jLabel3.setText(name);

        behaviouralproblem = ((WorkRequestDoctor) req).getProblem();

        txtbehaviouralProb.setText(behaviouralproblem);
        //populateReqTable();  

    }

    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestCaregiverJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtmessage = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbehaviouralProb = new javax.swing.JTextField();
        txtreport = new javax.swing.JTextField();
        reportjButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        requestCaregiverJButton.setBackground(new java.awt.Color(0, 0, 0));
        requestCaregiverJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        requestCaregiverJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestCaregiverJButton.setText("REQUEST CAREGIVER");
        requestCaregiverJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestCaregiverJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MESSAGE");

        txtmessage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmessageActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        valueLabel.setText("<value>");

        jLabel3.setText("jLabel2");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseLabel.setText("ENTERPRISE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PATIENT NAME");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DOCTOR'S REQUEST TO CAREGIVER");

        txtbehaviouralProb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtreport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreportActionPerformed(evt);
            }
        });

        reportjButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportjButton1.setText("ATTACH REPORT OF PATIENT");
        reportjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportjButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("REPORT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("BEHAVIOURAL PROBLEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtbehaviouralProb, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtreport, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(requestCaregiverJButton)
                        .addGap(140, 140, 140)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportjButton1)
                .addGap(243, 243, 243))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(610, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(587, 587, 587))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtreport, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtbehaviouralProb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(requestCaregiverJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(331, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestCaregiverJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestCaregiverJButtonActionPerformed
        if (txtreport.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please attach file", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String message = txtmessage.getText();
        String behaviouralProb = txtbehaviouralProb.getText();
        if (message.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter message for Child Request");
            return;
        }
        WorkRequestCaretaker request = new WorkRequestCaretaker();

        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatusatCaretaker("Sent");
        request.setProblem(behaviouralProb);
        request.setReport(txtreport.getText());
        request.setPatient(patient);

        Organization org = null;
        Enterprise ent = null;
        for (Enterprise e : entdir.getEnterpriseList()) {

            for (Organization organization : e.getOrgDir().getOrganizationList()) {
                if (organization instanceof CaregiverOrganization) {
                    org = organization;
                    ent = e;

                    break;
                }
            }

        }

        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);

        }

        JOptionPane.showMessageDialog(this, "Message Sent to Caregiver Department");
        //  populateReqTable();  
        txtbehaviouralProb.setText("");
        txtmessage.setText("");
        txtreport.setText("");


    }//GEN-LAST:event_requestCaregiverJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreportActionPerformed
    JFileChooser chooser = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("txt", "doc", "pdf");


    private void reportjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportjButton1ActionPerformed
        try {
            chooser.setFileFilter(filter);
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            txtreport.setText(filename);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Attach report of patient", "Warning", JOptionPane.WARNING_MESSAGE);
            return;

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_reportjButton1ActionPerformed

    private void txtmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton reportjButton1;
    private javax.swing.JButton requestCaregiverJButton;
    private javax.swing.JTextField txtbehaviouralProb;
    private javax.swing.JTextField txtmessage;
    private javax.swing.JTextField txtreport;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
