/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheetal
 */
public class CreateProductJPanel extends javax.swing.JPanel {

        private Product product;
    /**
     * Creates new form CreateProductJPanel
     */
    public CreateProductJPanel(Product product) {
        initComponents();
        this.product= product;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbBatteryStatus = new javax.swing.JComboBox<>();
        cmbEngineStatus = new javax.swing.JComboBox<>();
        cmboilStatus = new javax.swing.JComboBox<>();
        txtcarManufacturingYear = new javax.swing.JTextField();
        txtcarModel = new javax.swing.JTextField();
        txtVehicleID = new javax.swing.JTextField();
        cmbFuel = new javax.swing.JComboBox<>();
        txtMiles = new javax.swing.JTextField();
        txtServiceDate = new javax.swing.JTextField();
        txtServiceDescription = new javax.swing.JTextField();
        txtcustomerName = new javax.swing.JTextField();
        txtphoneNumber = new javax.swing.JTextField();
        txtcustomerEmailAddress = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();

        jLabel1.setText("Car Manufacturing year");

        jLabel2.setText("Car Model");

        jLabel3.setText("jLabel1");

        jLabel4.setText("Fuel");

        jLabel5.setText("Vehicle ID");

        jLabel6.setText("Miles");

        jLabel7.setText("Battery Status");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Car Service Logging");

        jLabel9.setText("Engine Status");

        jLabel10.setText("Oil Status");

        jLabel11.setText("Service Date");

        jLabel12.setText("Service Description");

        jLabel13.setText("Customer Name");

        jLabel14.setText("Customer Phone Number");

        jLabel15.setText("Customer Email ID");

        cmbBatteryStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old" }));
        cmbBatteryStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBatteryStatusActionPerformed(evt);
            }
        });

        cmbEngineStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Working", "Not Working" }));

        cmboilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full", "Half", "More than half", "Less than half" }));

        txtcarManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcarManufacturingYearActionPerformed(evt);
            }
        });

        cmbFuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNG", "Petrol", "Diesel" }));

        txtServiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceDateActionPerformed(evt);
            }
        });

        txtphoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneNumberActionPerformed(evt);
            }
        });

        txtcustomerEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomerEmailAddressActionPerformed(evt);
            }
        });

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcustomerEmailAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtphoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcustomerName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtServiceDescription, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtServiceDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmboilStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE)
                            .addComponent(cmbEngineStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBatteryStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMiles, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehicleID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFuel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcarModel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcarManufacturingYear)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)))))
                .addGap(299, 299, 299))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jLabel3)
                    .addContainerGap(609, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcarManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbBatteryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEngineStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmboilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtServiceDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtcustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtcustomerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnsubmit)
                .addGap(205, 205, 205))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(695, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBatteryStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBatteryStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBatteryStatusActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        int flag  = 0;
        flag = validator();
        if(flag == 1) {
        product.setCarManufacturingYear(txtcarManufacturingYear.getText().trim());
        product.setCarModel(txtcarModel.getText().trim());
        product.setFuel(cmbFuel.getSelectedItem().toString());
        product.setVehicleID(txtVehicleID.getText().trim()); 
        product.setMiles(txtMiles.getText().trim()); 
        product.setBatteryStatus(cmbBatteryStatus.getSelectedItem().toString()); 
        product.setEngineStatus(cmbEngineStatus.getSelectedItem().toString()); 
        product.setOilStatus(cmboilStatus.getSelectedItem().toString()); 
        product.setServiceDate(txtServiceDate.getText().trim()); 
        product.setServiceDescription(txtServiceDescription.getText().trim()); 
        product.setCustomerName(txtcustomerName.getText().trim());
        product.setCustomerPhoneNumber(txtphoneNumber.getText().trim()); 
        product.setCustomerEmailAddress(txtcustomerEmailAddress.getText().trim()); 
        JOptionPane.showMessageDialog(null, "Car Details Created Successfully", "Success", JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    
  
    
    private void txtcarManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarManufacturingYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarManufacturingYearActionPerformed

    private void txtServiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceDateActionPerformed

    private void txtcustomerEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomerEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomerEmailAddressActionPerformed

    private void txtphoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> cmbBatteryStatus;
    private javax.swing.JComboBox<String> cmbEngineStatus;
    private javax.swing.JComboBox<String> cmbFuel;
    private javax.swing.JComboBox<String> cmboilStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtMiles;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtServiceDescription;
    private javax.swing.JTextField txtVehicleID;
    private javax.swing.JTextField txtcarManufacturingYear;
    private javax.swing.JTextField txtcarModel;
    private javax.swing.JTextField txtcustomerEmailAddress;
    private javax.swing.JTextField txtcustomerName;
    private javax.swing.JTextField txtphoneNumber;
    // End of variables declaration//GEN-END:variables

 private int validator(){
            if((txtcarManufacturingYear.getText().trim().length() == 0)||(!txtcarManufacturingYear.getText().matches("^?(19[\\d]{2}|20[\\d]{2}|2100)$"))){
                   JOptionPane.showMessageDialog(this,"Enter Car Manufacturing date in 'yyyy' format in the range 1900-2100");
                   return 2;
            }
           // else if(!txtcarManufacturingYear.getText().matches("^?(19[\\d]{2}|20[\\d]{2}|2100)$"))
           // JOptionPane.showMessageDialog(this,"Enter the year of car make in 'yyyy' format from 1900-2100");
            else if (txtcarModel.getText().trim().length() == 0) {
                   JOptionPane.showMessageDialog(this,"Enter name of the Car Model");
                   return 2;
            }       
            else if (txtVehicleID.getText().trim().length() == 0) {
                   JOptionPane.showMessageDialog(this,"Enter the Vehicle ID");
                   return 2;
            }       
            else if ((txtMiles.getText().trim().length() == 0)||(!txtMiles.getText().matches("^[0-9]+$"))) {
                   JOptionPane.showMessageDialog(this,"Enter Number of miles in digits");
                   return 2;
            }       
            else if((txtServiceDate.getText().trim().length() == 0)||(!txtServiceDate.getText().matches("^(0?[1-9]|1[012])[-/]?(0?[1-9]|[12][0-9]|3[01])[-/]?(19[\\d]{2}|20[\\d]{2}|2100)$"))) {
            JOptionPane.showMessageDialog(this,"Enter Previous service date of the car in 'mm/dd/yyyy' format");
            return 2;
            }
            else if (txtServiceDescription.getText().trim().length() == 0) {
                   JOptionPane.showMessageDialog(this,"Enter service Description");
                   return 2;
            }       
            else if (txtcustomerName.getText().trim().length() == 0) {
                   JOptionPane.showMessageDialog(this,"Enter Customer Name");
                   return 2;
            }       
            else if ((txtphoneNumber.getText().trim().length() == 0)||(!txtphoneNumber.getText().matches("^(\\([0-9]{3}\\)|[0-9]{3}-)[0-9]{3}-[0-9]{4}$"))) {
                   JOptionPane.showMessageDialog(this,"Enter Customer Phone Number in 'xxx-xxx-xxxx' format");
                   return 2;
            }
           else if (txtcustomerEmailAddress.getText().trim().length() == 0) {
                   JOptionPane.showMessageDialog(this,"Please enter e-mail address");
                   return 2;
           }       
           else {
               return 1;
           }
    }
 
}
