/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CaregiverRole;


import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Security.Activity;
import Business.Security.SessionLog;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WorkRequestCaretaker;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.Date;
import javax.media.ControllerEvent;
import javax.media.ControllerListener;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Prashant
 */
public class ProcessWorkRequestJPanelC extends javax.swing.JPanel implements ActionListener, ControllerListener {

    /**
     * Creates new form ProcessWorkRequestJPanelC
     */
        private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private EnterpriseDirectory entdir;
    private WorkRequest req;
    private UserAccount account;
   private Patient patient;
    private JPanel userProcessContainer;
    private SessionLog session;
    public ProcessWorkRequestJPanelC( JPanel userProcessContainer,UserAccount account,Enterprise enterprise,EnterpriseDirectory entdir,WorkRequest req,Patient patient,SessionLog session ) {
        initComponents();
           this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account= account;
       this.entdir=entdir;
        this.patient=patient;
        this.req=req;
        this.session=session;
              Activity a = session.getActivityDirectory().addActivity();
        a.setActivityTime(new Date());
        a.setPanelName("ProcessWorkRequestJPanelC");
          btnangryOutburst.setEnabled(false);
            btnroutine.setEnabled(false);
             btnassignteacher.setEnabled(false);
             btnplaymusic.setEnabled(false);
             btnphotoalbum.setEnabled(false);
             

   
        
        if(((WorkRequestCaretaker)req).getProblem().equals("Angry Outbursts and Physical Aggression"))
        {
            btnangryOutburst.setEnabled(true);
            btnroutine.setEnabled(true);
        }
        else if(((WorkRequestCaretaker)req).getProblem().equals("Hand-wringing, Pacing and Rocking"))
        {

           btnassignteacher.setEnabled(true);
        }
        else if(((WorkRequestCaretaker)req).getProblem().equals("Repeating Stories and Leaving the House Unassisted"))
        {
           btnphotoalbum.setEnabled(true);
        }
        else if(((WorkRequestCaretaker)req).getProblem().equals("Sleep Problems and Sundowning"))
        {
           btnplaymusic.setEnabled(true);
        }
        else
        {
            btnplaymusic.setEnabled(true);
        }
                
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnangryOutburst = new javax.swing.JButton();
        btnassignteacher = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtreport = new javax.swing.JTextField();
        btnroutine = new javax.swing.JButton();
        btnplaymusic = new javax.swing.JButton();
        btnphotoalbum = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PROCESS REQUEST FROM DOCTOR");

        btnangryOutburst.setBackground(new java.awt.Color(0, 0, 0));
        btnangryOutburst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangryOutburst.setForeground(new java.awt.Color(255, 255, 255));
        btnangryOutburst.setText("DAILY ROUTINE REMINDER NOTES");
        btnangryOutburst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangryOutburstActionPerformed(evt);
            }
        });

        btnassignteacher.setBackground(new java.awt.Color(0, 0, 0));
        btnassignteacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnassignteacher.setForeground(new java.awt.Color(255, 255, 255));
        btnassignteacher.setText("ASSIGN TO YOGA TEACHER");
        btnassignteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassignteacherActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("<< BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtreport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreportActionPerformed(evt);
            }
        });

        btnroutine.setBackground(new java.awt.Color(0, 0, 0));
        btnroutine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnroutine.setForeground(new java.awt.Color(255, 255, 255));
        btnroutine.setText("ATTACH DAILY ROUTINE REPORT");
        btnroutine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroutineActionPerformed(evt);
            }
        });

        btnplaymusic.setBackground(new java.awt.Color(0, 0, 0));
        btnplaymusic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnplaymusic.setForeground(new java.awt.Color(255, 255, 255));
        btnplaymusic.setText("PLAY SOOTHING AUDIO");
        btnplaymusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaymusicActionPerformed(evt);
            }
        });

        btnphotoalbum.setBackground(new java.awt.Color(0, 0, 0));
        btnphotoalbum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnphotoalbum.setForeground(new java.awt.Color(255, 255, 255));
        btnphotoalbum.setText("SHOW PHOTO ALBUM");
        btnphotoalbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotoalbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtreport, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnroutine))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnangryOutburst, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(btnplaymusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnphotoalbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnassignteacher, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtreport, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnroutine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnassignteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnangryOutburst, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnphotoalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnplaymusic, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CaregiverWorkAreaJPanel dwjp = (CaregiverWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreportActionPerformed
JFileChooser chooser = new JFileChooser();
FileNameExtensionFilter filter = new FileNameExtensionFilter("txt", "doc", "pdf");
    private void btnroutineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroutineActionPerformed
        try{
            chooser.setFileFilter(filter);
            JFileChooser chooser=new JFileChooser();
            chooser.showOpenDialog(null);
            File f=chooser.getSelectedFile();
            String filename= f.getAbsolutePath();
            txtreport.setText(filename);
            if(txtreport.getText().trim().length()==0)
            {
                JOptionPane.showMessageDialog(this, "Please attach file","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Attach report of patient","Warning",JOptionPane.WARNING_MESSAGE);
            return;

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroutineActionPerformed

    private void btnangryOutburstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangryOutburstActionPerformed
        try
        {
       
      Desktop.getDesktop().open(new File(txtreport.getText()));
        }
        catch(IOException e)
        {
            
        }
           
          
        
    }//GEN-LAST:event_btnangryOutburstActionPerformed

    private void btnassignteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassignteacherActionPerformed
        
        RequestTeacherJPanel processWorkRequestJPanel = new RequestTeacherJPanel( userProcessContainer, account, enterprise, entdir, req,patient,session);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnassignteacherActionPerformed

    private void btnplaymusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaymusicActionPerformed
          InputStream in;
     try{
        in=new FileInputStream(new File("E:\\AlzheimerPatientCare\\MoodyLoop.wav"));
        AudioStream audios=new AudioStream(in);
        AudioPlayer.player.start(audios);
     }
    catch(IOException error)
        {JOptionPane.showMessageDialog(this, error.getMessage());
        }

    }//GEN-LAST:event_btnplaymusicActionPerformed

    private void btnphotoalbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotoalbumActionPerformed
      PhotoAlbumJPanel processWorkRequestJPanel = new PhotoAlbumJPanel( userProcessContainer, account, enterprise, entdir, req,patient,session);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnphotoalbumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnangryOutburst;
    private javax.swing.JButton btnassignteacher;
    private javax.swing.JButton btnphotoalbum;
    private javax.swing.JButton btnplaymusic;
    private javax.swing.JButton btnroutine;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtreport;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void controllerUpdate(ControllerEvent ce) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
